COMMAND:
@cli.command(name="prep", help="Prepare files for performing MMORESEQS search via prep-search. Takes ")
@click.argument("target_filepath", type=str)
@click.argument("query_filepath", type=str)
@click.argument("temp_filepath", type=str)
@click.option("--dbg", type=(bool), default=(True), help="Outputs debugger info.", hidden=True, nargs=1)
@click.option("--dbg-viz", type=(bool), default=(True), help="Outputs visualization debugger info.", hidden=True, nargs=1)
@click.option("--debugout", type=(bool), default=(True), help="Specify path to output debugger info.", hidden=True, nargs=1)
@click.option("--verbose", type=(int), default=(3), help="Amount of output: 0=quiet, 1=errors, 2=warnings, 3=info", hidden=False, nargs=1)
@click.option("--num-threads", type=(int), default=(1), help="Number of parallel threads.", hidden=False, nargs=1)
@click.option("--search-type", type=(str), default=("P2S"), help="Set type of search: P2S=profile-to-sequence, S2S=sequence-to-sequence", hidden=False, nargs=1)
@click.option("--use-pvals", type=(bool), default=(False), help="Use P-values (as opposed to default E-values) for reporting and scoring thresholds.", hidden=False, nargs=1)
@click.option("--eval", type=(bool), default=(True), help="Set E-value filter threshold cutoff score for reporting.", hidden=False, nargs=1)
@click.option("--program-mmseqs", type=(str), default=("None"), help="Specify location of MMSEQS program.", hidden=False, nargs=1)
@click.option("--program-hmmer", type=(str), default=("None"), help="Specify location of HMMER program.", hidden=False, nargs=1)
@click.option("--program-mmoreseqs", type=(str), default=("None"), help="Specify location of MMORESEQS program.", hidden=False, nargs=1)
@click.option("--script-dir", type=(str), default=("None"), help="Specify location of MMORESEQS scripts directory.", hidden=False, nargs=1)
@click.option("--local-tools", type=(bool), default=(False), help="Specify whether to use locally tools or globally installed tools.", hidden=False, nargs=1)
@click.option("--guess-ftype", type=(bool), default=(True), help="Specify whether to infer filetype of target and query input. Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=1)
@click.option("--mmoreseqs-ftype", type=(str, str, str, str), default=("None", "None", "None", "None"), help="Specify filetype of [0] target, [1] query, [2] MMSEQS target, [3] MMSEQS query.  Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=4)

COMMAND:
@cli.command(name="prep-search", help="Runs full MMORESEQS search on prepared file directory.")
@click.argument("temp_filepath", type=str)
@click.option("--dbg", type=(bool), default=(True), help="Outputs debugger info.", hidden=True, nargs=1)
@click.option("--dbg-viz", type=(bool), default=(True), help="Outputs visualization debugger info.", hidden=True, nargs=1)
@click.option("--debugout", type=(bool), default=(True), help="Specify path to output debugger info.", hidden=True, nargs=1)
@click.option("--verbose", type=(int), default=(3), help="Amount of output: 0=quiet, 1=errors, 2=warnings, 3=info", hidden=False, nargs=1)
@click.option("--num-threads", type=(int), default=(1), help="Number of parallel threads.", hidden=False, nargs=1)
@click.option("--search-type", type=(str), default=("P2S"), help="Set type of search: P2S=profile-to-sequence, S2S=sequence-to-sequence", hidden=False, nargs=1)
@click.option("--run-mmseqs", type=(bool), default=(True), help="Run MMSEQS stage of MMORESEQS pipeline.", hidden=False, nargs=1)
@click.option("--run-mmseqs-pref", type=(bool), default=(True), help="Run MMSEQS prefilter for MMSEQS stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-mmseqs-align", type=(bool), default=(True), help="Run Viterbi alignment for MMSEQS stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-convert", type=(bool), default=(True), help="Convert results from MMSEQS to a format that can be interpreted by MMORE.", hidden=False, nargs=1)
@click.option("--run-mmore", type=(bool), default=(True), help="Run MMORE stage of the MMORESEQS pipeline.", hidden=False, nargs=1)
@click.option("--use-pvals", type=(bool), default=(False), help="Use P-values (as opposed to default E-values) for reporting and scoring thresholds.", hidden=False, nargs=1)
@click.option("--eval", type=(bool), default=(True), help="Set E-value filter threshold cutoff score for reporting.", hidden=False, nargs=1)
@click.option("--program-mmseqs", type=(str), default=("None"), help="Specify location of MMSEQS program.", hidden=False, nargs=1)
@click.option("--program-hmmer", type=(str), default=("None"), help="Specify location of HMMER program.", hidden=False, nargs=1)
@click.option("--program-mmoreseqs", type=(str), default=("None"), help="Specify location of MMORESEQS program.", hidden=False, nargs=1)
@click.option("--script-dir", type=(str), default=("None"), help="Specify location of MMORESEQS scripts directory.", hidden=False, nargs=1)
@click.option("--index", type=(str, str), default=("None", "None"), help="Specify location of [0] target and [1] query index files.", hidden=False, nargs=2)
@click.option("--local-tools", type=(bool), default=(False), help="Specify whether to use locally tools or globally installed tools.", hidden=False, nargs=1)
@click.option("--guess-ftype", type=(bool), default=(True), help="Specify whether to infer filetype of target and query input. Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=1)
@click.option("--mmoreseqs-ftype", type=(str, str, str, str), default=("None", "None", "None", "None"), help="Specify filetype of [0] target, [1] query, [2] MMSEQS target, [3] MMSEQS query.  Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=4)
@click.option("--alpha", type=(bool), default=(True), help="Set MMORE alpha parameter. Determines X-drop below current anti-diagonal max score accepted.", hidden=False, nargs=1)
@click.option("--beta", type=(bool), default=(True), help="Set MMORE beta parameter. Determines X-drop below global max score accepted.", hidden=False, nargs=1)
@click.option("--gamma", type=(bool), default=(True), help="Set MMORE gamma parameter. Determines X-drop below global max score before ending search.", hidden=False, nargs=1)
@click.option("--hard-limit", type=(bool), default=(True), help="Set MMORE hard limit parameter. Determines lowest permissable score before ending search.", hidden=False, nargs=1)
@click.option("--run-prep", type=(bool), default=(True), help="Run file preparation for the MMORE stage of pipeline", hidden=False, nargs=1)
@click.option("--run-bias", type=(bool), default=(True), help="Use null bias during the MMORE stage of pipeline", hidden=False, nargs=1)
@click.option("--run-full", type=(bool), default=(True), help="Run full quadratic search during the MMORE stage of pipeline. Overrides alpha/beta/gamma parameters.", hidden=False, nargs=1)
@click.option("--run-domains", type=(bool), default=(True), help="Run over all domains found by MMSEQS for all target-query pairs during MMORE stage of pipeline. Alternatively, only uses the searches the top domain.", hidden=False, nargs=1)
@click.option("--run-vit-mmore", type=(bool), default=(True), help="Run full viterbi during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-vit", type=(bool), default=(True), help="Run viterbi during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-post", type=(bool), default=(True), help="Run posterior during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--range", type=(bool), default=(True), help="Specify [0] start and [1] stop range of targets to search against the query database.", hidden=False, nargs=1)
@click.option("--run-filter", type=(bool), default=(True), help="Run all filters during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-vit-filter", type=(bool), default=(True), help="Run viterbi filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-cld-filter", type=(bool), default=(True), help="Run cloud filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-fwd-filter", type=(bool), default=(True), help="Run forward filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--vit-filter", type=(bool), default=(True), help="Set viterbi filter threshold cutoff score.", hidden=False, nargs=1)
@click.option("--cld-filter", type=(bool), default=(True), help="Set cloud filter threshold cutoff score.", hidden=False, nargs=1)
@click.option("--fwd-filter", type=(bool), default=(True), help="Set forward filter threshold cutoff score.", hidden=False, nargs=1)

COMMAND:
@cli.command(name="mmseqs-search", help="Runs MMSEQS stage of MMORESEQS search on target and query databases.")
@click.argument("target_filepath", type=str)
@click.argument("query_filepath", type=str)
@click.option("--dbg", type=(bool), default=(True), help="Outputs debugger info.", hidden=True, nargs=1)
@click.option("--dbg-viz", type=(bool), default=(True), help="Outputs visualization debugger info.", hidden=True, nargs=1)
@click.option("--debugout", type=(bool), default=(True), help="Specify path to output debugger info.", hidden=True, nargs=1)
@click.option("--verbose", type=(int), default=(3), help="Amount of output: 0=quiet, 1=errors, 2=warnings, 3=info", hidden=False, nargs=1)
@click.option("--num-threads", type=(int), default=(1), help="Number of parallel threads.", hidden=False, nargs=1)
@click.option("--search-type", type=(str), default=("P2S"), help="Set type of search: P2S=profile-to-sequence, S2S=sequence-to-sequence", hidden=False, nargs=1)
@click.option("--use-pvals", type=(bool), default=(False), help="Use P-values (as opposed to default E-values) for reporting and scoring thresholds.", hidden=False, nargs=1)
@click.option("--eval", type=(bool), default=(True), help="Set E-value filter threshold cutoff score for reporting.", hidden=False, nargs=1)
@click.option("--program-mmseqs", type=(str), default=("None"), help="Specify location of MMSEQS program.", hidden=False, nargs=1)
@click.option("--program-hmmer", type=(str), default=("None"), help="Specify location of HMMER program.", hidden=False, nargs=1)
@click.option("--program-mmoreseqs", type=(str), default=("None"), help="Specify location of MMORESEQS program.", hidden=False, nargs=1)
@click.option("--script-dir", type=(str), default=("None"), help="Specify location of MMORESEQS scripts directory.", hidden=False, nargs=1)
@click.option("--index", type=(str, str), default=("None", "None"), help="Specify location of [0] target and [1] query index files.", hidden=False, nargs=2)
@click.option("--local-tools", type=(bool), default=(False), help="Specify whether to use locally tools or globally installed tools.", hidden=False, nargs=1)
@click.option("--guess-ftype", type=(bool), default=(True), help="Specify whether to infer filetype of target and query input. Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=1)
@click.option("--mmoreseqs-ftype", type=(str, str, str, str), default=("None", "None", "None", "None"), help="Specify filetype of [0] target, [1] query, [2] MMSEQS target, [3] MMSEQS query.  Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=4)
@click.option("--mmoreseqs-main-ftype", type=(bool), default=(True), help="Specify filetype of [0] target and [1] query input.", hidden=False, nargs=1)
@click.option("--temp", type=(bool), default=(True), help="Specify temporary working folder location.", hidden=False, nargs=1)
@click.option("--mmseqs-m8", type=(bool), default=(True), help="Specify location of input MMSEQS .m8 results file.", hidden=False, nargs=1)
@click.option("--dbsizes", type=(bool), default=(True), help="Specify size of [0] target and [1] query databases.", hidden=False, nargs=1)

COMMAND:
@cli.command(name="mmore-search", help="Runs MMORE stage of MMORESEQS search on target and query databases, using results from MMSEQS stage.")
@click.argument("target_filepath", type=str)
@click.argument("query_filepath", type=str)
@click.argument("mmseqs_m8_filepath", type=str)
@click.option("--dbg", type=(bool), default=(True), help="Outputs debugger info.", hidden=True, nargs=1)
@click.option("--dbg-viz", type=(bool), default=(True), help="Outputs visualization debugger info.", hidden=True, nargs=1)
@click.option("--debugout", type=(bool), default=(True), help="Specify path to output debugger info.", hidden=True, nargs=1)
@click.option("--verbose", type=(int), default=(3), help="Amount of output: 0=quiet, 1=errors, 2=warnings, 3=info", hidden=False, nargs=1)
@click.option("--num-threads", type=(int), default=(1), help="Number of parallel threads.", hidden=False, nargs=1)
@click.option("--search-type", type=(str), default=("P2S"), help="Set type of search: P2S=profile-to-sequence, S2S=sequence-to-sequence", hidden=False, nargs=1)
@click.option("--use-pvals", type=(bool), default=(False), help="Use P-values (as opposed to default E-values) for reporting and scoring thresholds.", hidden=False, nargs=1)
@click.option("--eval", type=(bool), default=(True), help="Set E-value filter threshold cutoff score for reporting.", hidden=False, nargs=1)
@click.option("--program-mmseqs", type=(str), default=("None"), help="Specify location of MMSEQS program.", hidden=False, nargs=1)
@click.option("--program-hmmer", type=(str), default=("None"), help="Specify location of HMMER program.", hidden=False, nargs=1)
@click.option("--program-mmoreseqs", type=(str), default=("None"), help="Specify location of MMORESEQS program.", hidden=False, nargs=1)
@click.option("--script-dir", type=(str), default=("None"), help="Specify location of MMORESEQS scripts directory.", hidden=False, nargs=1)
@click.option("--index", type=(str, str), default=("None", "None"), help="Specify location of [0] target and [1] query index files.", hidden=False, nargs=2)
@click.option("--local-tools", type=(bool), default=(False), help="Specify whether to use locally tools or globally installed tools.", hidden=False, nargs=1)
@click.option("--guess-ftype", type=(bool), default=(True), help="Specify whether to infer filetype of target and query input. Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=1)
@click.option("--mmoreseqs-ftype", type=(str, str, str, str), default=("None", "None", "None", "None"), help="Specify filetype of [0] target, [1] query, [2] MMSEQS target, [3] MMSEQS query.  Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=4)
@click.option("--mmoreseqs-main-ftype", type=(bool), default=(True), help="Specify filetype of [0] target and [1] query input.", hidden=False, nargs=1)
@click.option("--temp", type=(bool), default=(True), help="Specify temporary working folder location.", hidden=False, nargs=1)
@click.option("--mmseqs-m8", type=(bool), default=(True), help="Specify location of input MMSEQS .m8 results file.", hidden=False, nargs=1)
@click.option("--dbsizes", type=(bool), default=(True), help="Specify size of [0] target and [1] query databases.", hidden=False, nargs=1)
@click.option("--alpha", type=(bool), default=(True), help="Set MMORE alpha parameter. Determines X-drop below current anti-diagonal max score accepted.", hidden=False, nargs=1)
@click.option("--beta", type=(bool), default=(True), help="Set MMORE beta parameter. Determines X-drop below global max score accepted.", hidden=False, nargs=1)
@click.option("--gamma", type=(bool), default=(True), help="Set MMORE gamma parameter. Determines X-drop below global max score before ending search.", hidden=False, nargs=1)
@click.option("--hard-limit", type=(bool), default=(True), help="Set MMORE hard limit parameter. Determines lowest permissable score before ending search.", hidden=False, nargs=1)
@click.option("--run-prep", type=(bool), default=(True), help="Run file preparation for the MMORE stage of pipeline", hidden=False, nargs=1)
@click.option("--run-bias", type=(bool), default=(True), help="Use null bias during the MMORE stage of pipeline", hidden=False, nargs=1)
@click.option("--run-full", type=(bool), default=(True), help="Run full quadratic search during the MMORE stage of pipeline. Overrides alpha/beta/gamma parameters.", hidden=False, nargs=1)
@click.option("--run-domains", type=(bool), default=(True), help="Run over all domains found by MMSEQS for all target-query pairs during MMORE stage of pipeline. Alternatively, only uses the searches the top domain.", hidden=False, nargs=1)
@click.option("--run-vit-mmore", type=(bool), default=(True), help="Run full viterbi during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-vit", type=(bool), default=(True), help="Run viterbi during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-post", type=(bool), default=(True), help="Run posterior during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--range", type=(bool), default=(True), help="Specify [0] start and [1] stop range of targets to search against the query database.", hidden=False, nargs=1)
@click.option("--run-filter", type=(bool), default=(True), help="Run all filters during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-vit-filter", type=(bool), default=(True), help="Run viterbi filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-cld-filter", type=(bool), default=(True), help="Run cloud filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-fwd-filter", type=(bool), default=(True), help="Run forward filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--vit-filter", type=(bool), default=(True), help="Set viterbi filter threshold cutoff score.", hidden=False, nargs=1)
@click.option("--cld-filter", type=(bool), default=(True), help="Set cloud filter threshold cutoff score.", hidden=False, nargs=1)
@click.option("--fwd-filter", type=(bool), default=(True), help="Set forward filter threshold cutoff score.", hidden=False, nargs=1)

COMMAND:
@cli.command(name="easy-search", help="Prepares file and completes full search on target and query databases.")
@click.argument("target_filepath", type=str)
@click.argument("query_filepath", type=str)
@click.argument("temp_filepath", type=str)
@click.option("--dbg", type=(bool), default=(True), help="Outputs debugger info.", hidden=True, nargs=1)
@click.option("--dbg-viz", type=(bool), default=(True), help="Outputs visualization debugger info.", hidden=True, nargs=1)
@click.option("--debugout", type=(bool), default=(True), help="Specify path to output debugger info.", hidden=True, nargs=1)
@click.option("--verbose", type=(int), default=(3), help="Amount of output: 0=quiet, 1=errors, 2=warnings, 3=info", hidden=False, nargs=1)
@click.option("--num-threads", type=(int), default=(1), help="Number of parallel threads.", hidden=False, nargs=1)
@click.option("--search-type", type=(str), default=("P2S"), help="Set type of search: P2S=profile-to-sequence, S2S=sequence-to-sequence", hidden=False, nargs=1)
@click.option("--use-pvals", type=(bool), default=(False), help="Use P-values (as opposed to default E-values) for reporting and scoring thresholds.", hidden=False, nargs=1)
@click.option("--eval", type=(bool), default=(True), help="Set E-value filter threshold cutoff score for reporting.", hidden=False, nargs=1)
@click.option("--program-mmseqs", type=(str), default=("None"), help="Specify location of MMSEQS program.", hidden=False, nargs=1)
@click.option("--program-hmmer", type=(str), default=("None"), help="Specify location of HMMER program.", hidden=False, nargs=1)
@click.option("--program-mmoreseqs", type=(str), default=("None"), help="Specify location of MMORESEQS program.", hidden=False, nargs=1)
@click.option("--script-dir", type=(str), default=("None"), help="Specify location of MMORESEQS scripts directory.", hidden=False, nargs=1)
@click.option("--local-tools", type=(bool), default=(False), help="Specify whether to use locally tools or globally installed tools.", hidden=False, nargs=1)
@click.option("--guess-ftype", type=(bool), default=(True), help="Specify whether to infer filetype of target and query input. Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=1)
@click.option("--mmoreseqs-ftype", type=(str, str, str, str), default=("None", "None", "None", "None"), help="Specify filetype of [0] target, [1] query, [2] MMSEQS target, [3] MMSEQS query.  Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=4)
@click.option("--alpha", type=(bool), default=(True), help="Set MMORE alpha parameter. Determines X-drop below current anti-diagonal max score accepted.", hidden=False, nargs=1)
@click.option("--beta", type=(bool), default=(True), help="Set MMORE beta parameter. Determines X-drop below global max score accepted.", hidden=False, nargs=1)
@click.option("--gamma", type=(bool), default=(True), help="Set MMORE gamma parameter. Determines X-drop below global max score before ending search.", hidden=False, nargs=1)
@click.option("--hard-limit", type=(bool), default=(True), help="Set MMORE hard limit parameter. Determines lowest permissable score before ending search.", hidden=False, nargs=1)
@click.option("--run-prep", type=(bool), default=(True), help="Run file preparation for the MMORE stage of pipeline", hidden=False, nargs=1)
@click.option("--run-bias", type=(bool), default=(True), help="Use null bias during the MMORE stage of pipeline", hidden=False, nargs=1)
@click.option("--run-full", type=(bool), default=(True), help="Run full quadratic search during the MMORE stage of pipeline. Overrides alpha/beta/gamma parameters.", hidden=False, nargs=1)
@click.option("--run-domains", type=(bool), default=(True), help="Run over all domains found by MMSEQS for all target-query pairs during MMORE stage of pipeline. Alternatively, only uses the searches the top domain.", hidden=False, nargs=1)
@click.option("--run-vit-mmore", type=(bool), default=(True), help="Run full viterbi during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-vit", type=(bool), default=(True), help="Run viterbi during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-post", type=(bool), default=(True), help="Run posterior during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--range", type=(bool), default=(True), help="Specify [0] start and [1] stop range of targets to search against the query database.", hidden=False, nargs=1)
@click.option("--run-filter", type=(bool), default=(True), help="Run all filters during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-vit-filter", type=(bool), default=(True), help="Run viterbi filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-cld-filter", type=(bool), default=(True), help="Run cloud filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--run-fwd-filter", type=(bool), default=(True), help="Run forward filter during the MMORE stage of pipeline.", hidden=False, nargs=1)
@click.option("--vit-filter", type=(bool), default=(True), help="Set viterbi filter threshold cutoff score.", hidden=False, nargs=1)
@click.option("--cld-filter", type=(bool), default=(True), help="Set cloud filter threshold cutoff score.", hidden=False, nargs=1)
@click.option("--fwd-filter", type=(bool), default=(True), help="Set forward filter threshold cutoff score.", hidden=False, nargs=1)

COMMAND:
@cli.command(name="version", help="Get version of MMOREseqs.")
@click.option("--dbg", type=(bool), default=(True), help="Outputs debugger info.", hidden=True, nargs=1)
@click.option("--dbg-viz", type=(bool), default=(True), help="Outputs visualization debugger info.", hidden=True, nargs=1)
@click.option("--debugout", type=(bool), default=(True), help="Specify path to output debugger info.", hidden=True, nargs=1)
@click.option("--verbose", type=(int), default=(3), help="Amount of output: 0=quiet, 1=errors, 2=warnings, 3=info", hidden=False, nargs=1)
@click.option("--num-threads", type=(int), default=(1), help="Number of parallel threads.", hidden=False, nargs=1)
@click.option("--search-type", type=(str), default=("P2S"), help="Set type of search: P2S=profile-to-sequence, S2S=sequence-to-sequence", hidden=False, nargs=1)
@click.option("--use-pvals", type=(bool), default=(False), help="Use P-values (as opposed to default E-values) for reporting and scoring thresholds.", hidden=False, nargs=1)
@click.option("--eval", type=(bool), default=(True), help="Set E-value filter threshold cutoff score for reporting.", hidden=False, nargs=1)
@click.option("--program-mmseqs", type=(str), default=("None"), help="Specify location of MMSEQS program.", hidden=False, nargs=1)
@click.option("--program-hmmer", type=(str), default=("None"), help="Specify location of HMMER program.", hidden=False, nargs=1)
@click.option("--program-mmoreseqs", type=(str), default=("None"), help="Specify location of MMORESEQS program.", hidden=False, nargs=1)
@click.option("--script-dir", type=(str), default=("None"), help="Specify location of MMORESEQS scripts directory.", hidden=False, nargs=1)
@click.option("--local-tools", type=(bool), default=(False), help="Specify whether to use locally tools or globally installed tools.", hidden=False, nargs=1)
@click.option("--guess-ftype", type=(bool), default=(True), help="Specify whether to infer filetype of target and query input. Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=1)
@click.option("--mmoreseqs-ftype", type=(str, str, str, str), default=("None", "None", "None", "None"), help="Specify filetype of [0] target, [1] query, [2] MMSEQS target, [3] MMSEQS query.  Options: HMM, FASTA, MSA, MM_MSA, HHM, MMDB, MMDB_S, MMDB_P.", hidden=False, nargs=4)

