name: Build and Smoke Test

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare build environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake python3-pip
      - name: Perform cmake build
        run: |
          make
